project:
  type: book

book:
  title: "Smarter Investieren - leicht erklärt"
  author: "Prof. Dr. Thomas Mählmann, Lehrstuhl für Banken und Finanzierung, Katholische Universität Eichstätt-Ingolstadt"
  date: "2025-11-23"
  chapters:
    - index.ipynb
    - kapitel1.ipynb
    - kapitel2.ipynb
    - kapitel3.ipynb
    - kapitel4.ipynb
    - kapitel5.ipynb
    - kapitel6.ipynb
    - kapitel7.ipynb
    - kapitel8.ipynb
    - kapitel9.ipynb
    - kapitel10.ipynb
    - kapitel11.ipynb
    - kapitel12.ipynb
    - kapitel13.ipynb
    - kapitel14.ipynb
    - kapitel15.ipynb
    - kapitel16.ipynb
    - kapitel17.ipynb
    - kapitel18.ipynb
    - kapitel19.ipynb

 


  sidebar:
    style: floating
    search: true
    collapse-level: 2

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-fold: true
    code-line-numbers: true
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css